# Generated by Django 4.0.6 on 2022-09-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargo',
            new_name='Materia',
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['descripcion'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materia'},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cargo',
            new_name='materia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
